export type Locale = 'us' | 'uk'
export type Mood = 'cosy' | 'fresh' | 'energised' | 'easy'
export type Avoid = 'meat' | 'fish' | 'mushroom' | 'cilantro' | 'spicy' | 'dairy'
export type Aisle = 'produce' | 'protein' | 'dairy' | 'bakery' | 'pantry' | 'frozen'

/** Shopping units. `whole` is a countable item (an onion, a lemon). */
export type QtyUnit = 'g' | 'ml' | 'tbsp' | 'tsp' | 'cans' | 'packs' | 'whole'

export type IngredientBase = {
  key: string
  us: string
  uk?: string
  aisle: Aisle
  staple?: boolean
}

export type Ingredient = IngredientBase & {
  /** Quantity for one serving. Basket totals = qtyPerServing × servings. */
  qtyPerServing: number
  unit: QtyUnit
}

export type Recipe = {
  id: string
  name: { us: string; uk?: string }
  time: number
  costPerServingUsd: number
  moods: Mood[]
  contains: Avoid[]
  makesLeftovers: boolean
  image: string
  ingredients: Ingredient[]
  steps: string[]
}

const i = (
  key: string,
  aisle: Aisle,
  us: string,
  uk?: string,
  staple = false,
): IngredientBase => ({ key, aisle, us, uk, staple })

/** Pins a per-serving quantity/unit onto a shared ingredient definition. */
const q = (base: IngredientBase, qtyPerServing: number, unit: QtyUnit): Ingredient => ({
  ...base,
  qtyPerServing,
  unit,
})

const garlic = i('garlic', 'produce', 'Garlic')
const ginger = i('ginger', 'produce', 'Fresh ginger')
const onion = i('onion', 'produce', 'Yellow onion', 'Brown onion')
const lemon = i('lemon', 'produce', 'Lemons')
const mint = i('mint', 'produce', 'Fresh mint')
const spinach = i('spinach', 'produce', 'Baby spinach')
const scallions = i('scallions', 'produce', 'Scallions', 'Spring onions')
const parmesan = i('parmesan', 'dairy', 'Parmesan')
const rice = i('rice', 'pantry', 'Jasmine rice')
const chicken = i('chicken-thighs', 'protein', 'Boneless chicken thighs')
const oliveOil = i('olive-oil', 'pantry', 'Olive oil', undefined, true)
const soy = i('soy', 'pantry', 'Soy sauce', undefined, true)

export const RECIPES: Recipe[] = [
  {
    id: 'miso-salmon',
    name: { us: 'Miso-honey salmon traybake' },
    time: 25,
    costPerServingUsd: 6.5,
    moods: ['fresh', 'energised'],
    contains: ['fish'],
    makesLeftovers: false,
    image: '/images/recipes/miso-salmon.webp',
    ingredients: [
      q(i('salmon', 'protein', 'Salmon fillets'), 150, 'g'),
      q(i('miso', 'pantry', 'White miso paste'), 1, 'tbsp'),
      q(i('honey', 'pantry', 'Honey', undefined, true), 1, 'tbsp'),
      q(i('broccolini', 'produce', 'Broccolini', 'Tenderstem broccoli'), 120, 'g'),
      q(scallions, 1, 'whole'),
      q(rice, 90, 'g'),
      q(soy, 1, 'tbsp'),
    ],
    steps: [
      'Heat the oven to 220°C / 425°F and line a tray.',
      'Whisk the miso, honey and soy into a glaze. Coat the salmon.',
      'Toss the broccolini with a little oil on the tray, nestle the salmon among it.',
      'Roast 12–14 minutes, until the salmon flakes easily.',
      'Steam the rice, then plate up with the salmon, broccolini and sliced scallions.',
    ],
  },
  {
    id: 'crispy-gnocchi',
    name: { us: 'Crispy gnocchi with burst tomatoes' },
    time: 20,
    costPerServingUsd: 3.2,
    moods: ['cosy', 'easy'],
    contains: ['dairy'],
    makesLeftovers: false,
    image: '/images/recipes/crispy-gnocchi.webp',
    ingredients: [
      q(i('gnocchi', 'pantry', 'Potato gnocchi'), 200, 'g'),
      q(i('cherry-tomatoes', 'produce', 'Cherry tomatoes'), 150, 'g'),
      q(garlic, 2, 'whole'),
      q(i('basil', 'produce', 'Fresh basil'), 0.25, 'packs'),
      q(parmesan, 20, 'g'),
      q(oliveOil, 1, 'tbsp'),
    ],
    steps: [
      'Heat the olive oil in a wide pan and add the gnocchi straight from the packet.',
      'Fry 6–8 minutes, turning, until golden and crisp. Tip onto plates.',
      'Add the tomatoes and sliced garlic to the pan; blister 3–4 minutes until they burst.',
      'Spoon the tomatoes over the gnocchi with torn basil and plenty of parmesan.',
    ],
  },
  {
    id: 'chickpea-curry',
    name: { us: 'Coconut chickpea curry' },
    time: 30,
    costPerServingUsd: 2.6,
    moods: ['cosy'],
    contains: [],
    makesLeftovers: true,
    image: '/images/recipes/chickpea-curry.webp',
    ingredients: [
      q(i('chickpeas', 'pantry', 'Canned chickpeas', 'Tinned chickpeas'), 0.5, 'cans'),
      q(i('coconut-milk', 'pantry', 'Coconut milk'), 0.5, 'cans'),
      q(spinach, 60, 'g'),
      q(onion, 0.5, 'whole'),
      q(garlic, 2, 'whole'),
      q(ginger, 10, 'g'),
      q(i('curry-powder', 'pantry', 'Mild curry powder', undefined, true), 1, 'tsp'),
      q(rice, 90, 'g'),
    ],
    steps: [
      'Soften the diced onion in a splash of oil for 5 minutes, then add the garlic and ginger.',
      'Stir in the curry powder for a minute, then the chickpeas and coconut milk.',
      'Simmer 10 minutes until glossy; wilt the spinach through at the end.',
      'Serve over steamed rice. Makes extra — tomorrow night is already handled.',
    ],
  },
  {
    id: 'chicken-tacos',
    name: { us: 'Chicken & charred corn tacos', uk: 'Chicken & charred sweetcorn tacos' },
    time: 25,
    costPerServingUsd: 4.8,
    moods: ['fresh', 'energised'],
    contains: ['meat', 'cilantro', 'dairy'],
    makesLeftovers: false,
    image: '/images/recipes/chicken-tacos.webp',
    ingredients: [
      q(chicken, 130, 'g'),
      q(i('corn', 'frozen', 'Frozen corn', 'Frozen sweetcorn'), 80, 'g'),
      q(i('tortillas', 'bakery', 'Small flour tortillas'), 3, 'whole'),
      q(i('lime', 'produce', 'Limes'), 1, 'whole'),
      q(i('cilantro', 'produce', 'Cilantro', 'Coriander'), 0.25, 'packs'),
      q(i('avocado', 'produce', 'Avocados'), 0.5, 'whole'),
      q(i('sour-cream', 'dairy', 'Sour cream', 'Soured cream'), 2, 'tbsp'),
    ],
    steps: [
      'Season the chicken and sear in a hot pan 5–6 minutes per side; rest, then slice.',
      'Char the corn in the same pan until spotty.',
      'Warm the tortillas and mash the avocado with lime and salt.',
      'Fill the tortillas with avocado, chicken and corn; finish with sour cream and cilantro.',
    ],
  },
  {
    id: 'shakshuka',
    name: { us: 'Shakshuka with feta & warm flatbread' },
    time: 20,
    costPerServingUsd: 2.9,
    moods: ['cosy', 'easy'],
    contains: ['dairy'],
    makesLeftovers: false,
    image: '/images/recipes/shakshuka.webp',
    ingredients: [
      q(i('eggs', 'dairy', 'Eggs'), 2, 'whole'),
      q(i('tomatoes-can', 'pantry', 'Canned crushed tomatoes', 'Tinned chopped tomatoes'), 0.5, 'cans'),
      q(i('pepper', 'produce', 'Red bell pepper', 'Red pepper'), 0.5, 'whole'),
      q(onion, 0.5, 'whole'),
      q(i('feta', 'dairy', 'Feta'), 40, 'g'),
      q(i('flatbread', 'bakery', 'Flatbreads'), 1, 'whole'),
      q(i('paprika', 'pantry', 'Smoked paprika', undefined, true), 1, 'tsp'),
    ],
    steps: [
      'Soften the sliced onion and pepper in a wide pan for 6–8 minutes.',
      'Add the paprika, then the tomatoes. Simmer 5 minutes until jammy.',
      'Make two wells per person, crack in the eggs, cover and cook 5–6 minutes.',
      'Crumble over the feta and serve with the flatbread warmed through.',
    ],
  },
  {
    id: 'lemon-orzo',
    name: { us: 'Lemony orzo with peas & mint' },
    time: 15,
    costPerServingUsd: 2.4,
    moods: ['fresh', 'easy'],
    contains: ['dairy'],
    makesLeftovers: false,
    image: '/images/recipes/lemon-orzo.webp',
    ingredients: [
      q(i('orzo', 'pantry', 'Orzo'), 90, 'g'),
      q(i('peas', 'frozen', 'Frozen peas'), 70, 'g'),
      q(lemon, 0.5, 'whole'),
      q(mint, 0.25, 'packs'),
      q(parmesan, 25, 'g'),
      q(oliveOil, 1, 'tbsp'),
    ],
    steps: [
      'Simmer the orzo in salted water until just tender, about 8 minutes.',
      'Add the peas for the last 2 minutes; drain, keeping a splash of the water.',
      'Stir through the olive oil, lemon zest and juice, parmesan and torn mint.',
      'Loosen with the pasta water until glossy and serve.',
    ],
  },
  {
    id: 'ginger-beef',
    name: { us: 'Sticky ginger beef noodles' },
    time: 15,
    costPerServingUsd: 5.2,
    moods: ['energised', 'easy'],
    contains: ['meat'],
    makesLeftovers: false,
    image: '/images/recipes/ginger-beef.webp',
    ingredients: [
      q(i('beef', 'protein', 'Flank steak, thinly sliced', 'Beef stir-fry strips'), 130, 'g'),
      q(i('noodles', 'pantry', 'Egg noodles'), 100, 'g'),
      q(ginger, 15, 'g'),
      q(garlic, 2, 'whole'),
      q(scallions, 2, 'whole'),
      q(i('bok-choy', 'produce', 'Baby bok choy', 'Pak choi'), 120, 'g'),
      q(soy, 1.5, 'tbsp'),
    ],
    steps: [
      'Get the noodles on. Toss the beef with half the soy and plenty of black pepper.',
      'Sear the beef in a screaming-hot pan for 2 minutes; lift out.',
      'Fry the ginger, garlic and whites of the scallions for 1 minute; add the bok choy.',
      'Return the beef with the noodles and the rest of the soy; toss sticky and serve.',
    ],
  },
  {
    id: 'squash-halloumi',
    name: { us: 'Roast squash & halloumi grain bowl' },
    time: 35,
    costPerServingUsd: 3.9,
    moods: ['cosy', 'fresh'],
    contains: ['dairy'],
    makesLeftovers: true,
    image: '/images/recipes/squash-halloumi.webp',
    ingredients: [
      q(i('squash', 'produce', 'Butternut squash'), 250, 'g'),
      q(i('halloumi', 'dairy', 'Halloumi'), 100, 'g'),
      q(i('quinoa', 'pantry', 'Quinoa'), 80, 'g'),
      q(i('arugula', 'produce', 'Arugula', 'Rocket'), 40, 'g'),
      q(i('pomegranate', 'produce', 'Pomegranate seeds'), 40, 'g'),
      q(i('tahini', 'pantry', 'Tahini'), 1.5, 'tbsp'),
      q(lemon, 0.5, 'whole'),
    ],
    steps: [
      'Roast the cubed squash at 220°C / 425°F with oil for 20 minutes.',
      'Cook the quinoa according to the packet, then fork it loose.',
      'Fry the halloumi slices until golden on both sides.',
      'Loosen the tahini with lemon juice and a little water into a drizzle.',
      'Pile the bowls high: quinoa, squash, halloumi, arugula, pomegranate, tahini. Makes extra.',
    ],
  },
  {
    id: 'mushroom-pasta',
    name: { us: 'Creamy mushroom & spinach pasta' },
    time: 20,
    costPerServingUsd: 3.1,
    moods: ['cosy', 'easy'],
    contains: ['mushroom', 'dairy'],
    makesLeftovers: false,
    image: '/images/recipes/mushroom-pasta.webp',
    ingredients: [
      q(i('mushrooms', 'produce', 'Cremini mushrooms', 'Chestnut mushrooms'), 150, 'g'),
      q(spinach, 60, 'g'),
      q(garlic, 2, 'whole'),
      q(i('cream', 'dairy', 'Heavy cream', 'Double cream'), 100, 'ml'),
      q(i('rigatoni', 'pantry', 'Rigatoni'), 100, 'g'),
      q(parmesan, 20, 'g'),
    ],
    steps: [
      'Boil the rigatoni. Meanwhile, fry the sliced mushrooms hard until golden, 6–8 minutes.',
      'Add the garlic for a minute, then the cream and a ladle of pasta water.',
      'Fold in the spinach until collapsed, then the drained pasta and parmesan.',
      'Season well and serve immediately.',
    ],
  },
  {
    id: 'harissa-chicken',
    name: { us: 'Harissa chicken with herby couscous' },
    time: 35,
    costPerServingUsd: 4.4,
    moods: ['energised', 'fresh'],
    contains: ['meat', 'spicy', 'dairy'],
    makesLeftovers: true,
    image: '/images/recipes/harissa-chicken.webp',
    ingredients: [
      q(chicken, 140, 'g'),
      q(i('harissa', 'pantry', 'Harissa paste'), 1.5, 'tbsp'),
      q(i('couscous', 'pantry', 'Couscous'), 90, 'g'),
      q(i('zucchini', 'produce', 'Zucchini', 'Courgette'), 0.5, 'whole'),
      q(lemon, 0.5, 'whole'),
      q(mint, 0.25, 'packs'),
      q(i('yogurt', 'dairy', 'Greek yogurt', 'Greek yoghurt'), 2, 'tbsp'),
    ],
    steps: [
      'Rub the chicken with half the harissa and roast at 220°C / 425°F with the zucchini for 22 minutes.',
      'Cover the couscous with equal boiling salted water; rest 5 minutes, then fork through.',
      'Stir the remaining harissa and lemon juice into the yogurt.',
      'Serve the chicken over the couscous with the herby yogurt spooned over. Makes extra.',
    ],
  },

  // ── Phase 1 additions: variety + diet coverage ─────────────────────────────

  {
    id: 'peanut-noodles',
    name: { us: 'Sesame peanut noodles' },
    time: 15,
    costPerServingUsd: 2.8,
    moods: ['easy', 'fresh'],
    contains: [],
    makesLeftovers: false,
    image: '/images/recipes/peanut-noodles.webp',
    ingredients: [
      q(i('rice-noodles', 'pantry', 'Rice noodles'), 100, 'g'),
      q(i('peanut-butter', 'pantry', 'Peanut butter'), 2, 'tbsp'),
      q(soy, 1, 'tbsp'),
      q(i('sesame-oil', 'pantry', 'Toasted sesame oil', undefined, true), 1, 'tsp'),
      q(ginger, 10, 'g'),
      q(garlic, 1, 'whole'),
      q(scallions, 1, 'whole'),
      q(i('lime', 'produce', 'Limes'), 0.5, 'whole'),
      q(i('carrot', 'produce', 'Carrots'), 1, 'whole'),
    ],
    steps: [
      'Cook the rice noodles and rinse under cold water to stop them sticking.',
      'Whisk the peanut butter, soy, sesame oil, grated ginger, garlic and lime juice with a splash of warm water until pourable.',
      'Shred the carrot into ribbons.',
      'Toss the noodles with the peanut sauce and pile into bowls with the carrot and scallions.',
    ],
  },
  {
    id: 'lentil-soup',
    name: { us: 'Smoky lentil & tomato soup' },
    time: 30,
    costPerServingUsd: 1.9,
    moods: ['cosy', 'easy'],
    contains: [],
    makesLeftovers: true,
    image: '/images/recipes/lentil-soup.webp',
    ingredients: [
      q(i('red-lentils', 'pantry', 'Red lentils'), 120, 'g'),
      q(i('tomatoes-can', 'pantry', 'Canned crushed tomatoes', 'Tinned chopped tomatoes'), 0.5, 'cans'),
      q(onion, 0.5, 'whole'),
      q(garlic, 2, 'whole'),
      q(i('carrot', 'produce', 'Carrots'), 1, 'whole'),
      q(i('cumin', 'pantry', 'Ground cumin', undefined, true), 1, 'tsp'),
      q(i('paprika', 'pantry', 'Smoked paprika', undefined, true), 1, 'tsp'),
      q(i('veg-stock', 'pantry', 'Vegetable stock'), 400, 'ml'),
    ],
    steps: [
      'Soften the chopped onion, carrot and garlic in a little oil for 6–8 minutes.',
      'Stir in the cumin and paprika, then the lentils, tomatoes and stock.',
      'Simmer 18–20 minutes until the lentils collapse into silk.',
      'Season boldly and serve with bread if there is any. Makes extra.',
    ],
  },
  {
    id: 'black-bean-tacos',
    name: { us: 'Smoky black bean tacos' },
    time: 20,
    costPerServingUsd: 2.5,
    moods: ['cosy', 'fresh'],
    contains: [],
    makesLeftovers: false,
    image: '/images/recipes/black-bean-tacos.webp',
    ingredients: [
      q(i('black-beans', 'pantry', 'Canned black beans', 'Tinned black beans'), 0.75, 'cans'),
      q(i('tortillas', 'bakery', 'Small flour tortillas'), 3, 'whole'),
      q(onion, 0.5, 'whole'),
      q(garlic, 1, 'whole'),
      q(i('cumin', 'pantry', 'Ground cumin', undefined, true), 1, 'tsp'),
      q(i('avocado', 'produce', 'Avocados'), 0.5, 'whole'),
      q(i('lime', 'produce', 'Limes'), 0.5, 'whole'),
      q(i('red-cabbage', 'produce', 'Red cabbage'), 100, 'g'),
      q(i('tomato', 'produce', 'Tomatoes'), 1, 'whole'),
    ],
    steps: [
      'Fry the onion and garlic until soft; add the beans with their liquid and the cumin.',
      'Mash roughly and simmer 5 minutes until thick and smoky.',
      'Shred the cabbage; dice the tomato; mash the avocado with lime.',
      'Warm the tortillas and build: beans, cabbage, tomato, avocado.',
    ],
  },
  {
    id: 'roast-veg-quinoa',
    name: { us: 'Roast veg & quinoa bowl with tahini' },
    time: 35,
    costPerServingUsd: 3.4,
    moods: ['fresh', 'cosy'],
    contains: [],
    makesLeftovers: true,
    image: '/images/recipes/roast-veg-quinoa.webp',
    ingredients: [
      q(i('quinoa', 'pantry', 'Quinoa'), 90, 'g'),
      q(i('sweet-potato', 'produce', 'Sweet potatoes'), 200, 'g'),
      q(i('red-onion', 'produce', 'Red onions'), 0.5, 'whole'),
      q(i('zucchini', 'produce', 'Zucchini', 'Courgette'), 0.5, 'whole'),
      q(i('pepper', 'produce', 'Red bell pepper', 'Red pepper'), 1, 'whole'),
      q(spinach, 40, 'g'),
      q(i('tahini', 'pantry', 'Tahini'), 1.5, 'tbsp'),
      q(lemon, 0.5, 'whole'),
    ],
    steps: [
      'Roast the cubed sweet potato, red onion, zucchini and pepper at 220°C / 425°F for 22 minutes.',
      'Cook the quinoa, then rest it covered for 5 minutes and fork it through.',
      'Whisk the tahini with lemon juice and cold water into a drizzle.',
      'Layer quinoa, roast veg and spinach; pour over the tahini. Makes extra.',
    ],
  },
  {
    id: 'tomato-basil-pasta',
    name: { us: 'Summer tomato & basil pasta' },
    time: 20,
    costPerServingUsd: 2.3,
    moods: ['fresh', 'easy'],
    contains: [],
    makesLeftovers: false,
    image: '/images/recipes/tomato-basil-pasta.webp',
    ingredients: [
      q(i('spaghetti', 'pantry', 'Spaghetti'), 100, 'g'),
      q(i('cherry-tomatoes', 'produce', 'Cherry tomatoes'), 150, 'g'),
      q(garlic, 2, 'whole'),
      q(i('basil', 'produce', 'Fresh basil'), 0.25, 'packs'),
      q(oliveOil, 1, 'tbsp'),
      q(lemon, 0.25, 'whole'),
    ],
    steps: [
      'Boil the spaghetti in well-salted water.',
      'Blister the tomatoes in the olive oil with the sliced garlic until they slump.',
      'Toss the pasta through with a ladle of pasta water and the lemon zest.',
      'Tear in the basil off the heat and serve.',
    ],
  },
  {
    id: 'tofu-stirfry',
    name: { us: 'Crispy tofu & veg stir-fry' },
    time: 20,
    costPerServingUsd: 3.0,
    moods: ['energised', 'easy'],
    contains: [],
    makesLeftovers: false,
    image: '/images/recipes/tofu-stirfry.webp',
    ingredients: [
      q(i('tofu', 'protein', 'Firm tofu'), 200, 'g'),
      q(i('broccoli', 'produce', 'Broccoli'), 120, 'g'),
      q(i('pepper', 'produce', 'Red bell pepper', 'Red pepper'), 0.5, 'whole'),
      q(ginger, 10, 'g'),
      q(garlic, 1, 'whole'),
      q(soy, 1.5, 'tbsp'),
      q(i('sesame-oil', 'pantry', 'Toasted sesame oil', undefined, true), 1, 'tsp'),
      q(rice, 90, 'g'),
    ],
    steps: [
      'Press the tofu, cube it, and fry in hot oil until golden on every side.',
      'Steam the rice. Stir-fry the broccoli and pepper for 4 minutes; add ginger and garlic.',
      'Return the tofu with the soy and sesame oil; toss until lacquered.',
      'Serve over the rice straight away.',
    ],
  },
  {
    id: 'butternut-soup',
    name: { us: 'Butternut & coconut soup' },
    time: 30,
    costPerServingUsd: 2.2,
    moods: ['cosy', 'easy'],
    contains: [],
    makesLeftovers: true,
    image: '/images/recipes/butternut-soup.webp',
    ingredients: [
      q(i('squash', 'produce', 'Butternut squash'), 300, 'g'),
      q(i('coconut-milk', 'pantry', 'Coconut milk'), 0.5, 'cans'),
      q(onion, 0.5, 'whole'),
      q(garlic, 2, 'whole'),
      q(ginger, 10, 'g'),
      q(i('curry-powder', 'pantry', 'Mild curry powder', undefined, true), 1, 'tsp'),
      q(i('veg-stock', 'pantry', 'Vegetable stock'), 250, 'ml'),
    ],
    steps: [
      'Soften the onion, garlic and ginger; add the curry powder for a minute.',
      'Add the cubed squash and stock; simmer 18 minutes until collapsing.',
      'Blend smooth with the coconut milk, then reheat gently and season.',
      'Serve with bread or just a spoon. Makes extra.',
    ],
  },
  {
    id: 'minestrone',
    name: { us: 'Hearty minestrone' },
    time: 35,
    costPerServingUsd: 2.1,
    moods: ['cosy'],
    contains: [],
    makesLeftovers: true,
    image: '/images/recipes/minestrone.webp',
    ingredients: [
      q(i('tomatoes-can', 'pantry', 'Canned crushed tomatoes', 'Tinned chopped tomatoes'), 0.5, 'cans'),
      q(i('white-beans', 'pantry', 'Canned cannellini beans', 'Tinned cannellini beans'), 0.5, 'cans'),
      q(i('carrot', 'produce', 'Carrots'), 1, 'whole'),
      q(i('celery', 'produce', 'Celery'), 1, 'whole'),
      q(onion, 0.5, 'whole'),
      q(garlic, 2, 'whole'),
      q(i('ditalini', 'pantry', 'Small soup pasta', 'Ditalini'), 60, 'g'),
      q(i('veg-stock', 'pantry', 'Vegetable stock'), 300, 'ml'),
      q(oliveOil, 1, 'tbsp'),
      q(i('oregano', 'pantry', 'Dried oregano', undefined, true), 1, 'tsp'),
    ],
    steps: [
      'Soften the chopped onion, carrot and celery in the olive oil, 8 minutes.',
      'Add garlic and oregano, then tomatoes, beans and stock. Simmer 15 minutes.',
      'Add the pasta and cook until tender, about 9 minutes.',
      'Season, finish with a drizzle of oil, and serve. Makes extra.',
    ],
  },
  {
    id: 'sweet-potato-chilli',
    name: { us: 'Sweet potato & black bean chilli' },
    time: 35,
    costPerServingUsd: 2.4,
    moods: ['cosy'],
    contains: ['spicy'],
    makesLeftovers: true,
    image: '/images/recipes/sweet-potato-chilli.webp',
    ingredients: [
      q(i('sweet-potato', 'produce', 'Sweet potatoes'), 200, 'g'),
      q(i('black-beans', 'pantry', 'Canned black beans', 'Tinned black beans'), 0.75, 'cans'),
      q(i('tomatoes-can', 'pantry', 'Canned crushed tomatoes', 'Tinned chopped tomatoes'), 0.5, 'cans'),
      q(onion, 0.5, 'whole'),
      q(garlic, 2, 'whole'),
      q(i('cumin', 'pantry', 'Ground cumin', undefined, true), 1, 'tsp'),
      q(i('paprika', 'pantry', 'Smoked paprika', undefined, true), 1, 'tsp'),
      q(i('chilli-powder', 'pantry', 'Chilli powder', 'Chili powder', true), 0.5, 'tsp'),
      q(i('lime', 'produce', 'Limes'), 0.25, 'whole'),
      q(rice, 80, 'g'),
    ],
    steps: [
      'Soften the onion and garlic; toast the cumin, paprika and chilli powder for a minute.',
      'Add the cubed sweet potato, tomatoes and a splash of water. Simmer 18 minutes.',
      'Add the beans and cook 5 more minutes until thick.',
      'Season with lime juice and serve over rice. Makes extra.',
    ],
  },
  {
    id: 'veggie-fried-rice',
    name: { us: 'Rainbow veggie fried rice' },
    time: 15,
    costPerServingUsd: 2.0,
    moods: ['easy'],
    contains: [],
    makesLeftovers: false,
    image: '/images/recipes/veggie-fried-rice.webp',
    ingredients: [
      q(rice, 90, 'g'),
      q(i('peas', 'frozen', 'Frozen peas'), 60, 'g'),
      q(i('carrot', 'produce', 'Carrots'), 0.5, 'whole'),
      q(i('corn', 'frozen', 'Frozen corn', 'Frozen sweetcorn'), 60, 'g'),
      q(scallions, 2, 'whole'),
      q(garlic, 1, 'whole'),
      q(ginger, 10, 'g'),
      q(soy, 1.5, 'tbsp'),
      q(i('sesame-oil', 'pantry', 'Toasted sesame oil', undefined, true), 1, 'tsp'),
    ],
    steps: [
      'Cook the rice and let it steam dry — day-old is even better.',
      'Fry the grated carrot, corn and peas in hot oil for 3 minutes.',
      'Add the garlic and ginger for a minute, then the rice; press it flat to catch some colour.',
      'Toss with the soy and sesame oil, finish with the scallions.',
    ],
  },
  {
    id: 'pesto-pasta',
    name: { us: 'Pesto rigatoni with green beans' },
    time: 15,
    costPerServingUsd: 3.0,
    moods: ['easy', 'fresh'],
    contains: ['dairy'],
    makesLeftovers: false,
    image: '/images/recipes/pesto-pasta.webp',
    ingredients: [
      q(i('rigatoni', 'pantry', 'Rigatoni'), 100, 'g'),
      q(i('pesto', 'pantry', 'Basil pesto'), 2, 'tbsp'),
      q(i('green-beans', 'produce', 'Green beans'), 100, 'g'),
      q(parmesan, 20, 'g'),
      q(lemon, 0.25, 'whole'),
    ],
    steps: [
      'Boil the rigatoni; add the trimmed green beans for the last 4 minutes.',
      'Reserve a cup of pasta water, then drain.',
      'Stir the pesto through with a splash of pasta water until every tube is coated.',
      'Finish with lemon zest and shaved parmesan.',
    ],
  },
  {
    id: 'turkey-meatballs',
    name: { us: 'Turkey meatballs in tomato sauce' },
    time: 35,
    costPerServingUsd: 4.2,
    moods: ['cosy'],
    contains: ['meat', 'dairy'],
    makesLeftovers: true,
    image: '/images/recipes/turkey-meatballs.webp',
    ingredients: [
      q(i('turkey-mince', 'protein', 'Turkey mince', 'Turkey mince'), 150, 'g'),
      q(i('breadcrumbs', 'pantry', 'Breadcrumbs'), 30, 'g'),
      q(i('eggs', 'dairy', 'Eggs'), 0.5, 'whole'),
      q(i('tomatoes-can', 'pantry', 'Canned crushed tomatoes', 'Tinned chopped tomatoes'), 0.5, 'cans'),
      q(onion, 0.5, 'whole'),
      q(garlic, 2, 'whole'),
      q(i('spaghetti', 'pantry', 'Spaghetti'), 90, 'g'),
      q(parmesan, 20, 'g'),
      q(i('oregano', 'pantry', 'Dried oregano', undefined, true), 1, 'tsp'),
    ],
    steps: [
      'Mix the turkey with the breadcrumbs, egg, half the garlic, salt and pepper; roll into small balls.',
      'Brown the meatballs in a wide pan, then lift out.',
      'Soften the onion and remaining garlic in the pan; add tomatoes and oregano. Return the meatballs.',
      'Simmer 15 minutes while the spaghetti boils.',
      'Serve with plenty of parmesan. Makes extra.',
    ],
  },
  {
    id: 'fish-tacos',
    name: { us: 'Baja fish tacos' },
    time: 25,
    costPerServingUsd: 5.0,
    moods: ['fresh', 'energised'],
    contains: ['fish', 'dairy'],
    makesLeftovers: false,
    image: '/images/recipes/fish-tacos.webp',
    ingredients: [
      q(i('white-fish', 'protein', 'White fish fillets', 'White fish fillets'), 150, 'g'),
      q(i('tortillas', 'bakery', 'Small flour tortillas'), 3, 'whole'),
      q(i('red-cabbage', 'produce', 'Red cabbage'), 100, 'g'),
      q(i('lime', 'produce', 'Limes'), 1, 'whole'),
      q(i('sour-cream', 'dairy', 'Sour cream', 'Soured cream'), 2, 'tbsp'),
      q(i('avocado', 'produce', 'Avocados'), 0.5, 'whole'),
      q(i('paprika', 'pantry', 'Smoked paprika', undefined, true), 1, 'tsp'),
    ],
    steps: [
      'Dust the fish with paprika, salt and lime zest; pan-fry 3 minutes per side.',
      'Toss the shredded cabbage with half the lime juice.',
      'Stir the sour cream with the rest of the lime and a pinch of salt.',
      'Warm the tortillas; flake in the fish; top with cabbage, avocado and the lime cream.',
    ],
  },
  {
    id: 'sausage-ragu',
    name: { us: 'Sausage & fennel ragu' },
    time: 35,
    costPerServingUsd: 3.8,
    moods: ['cosy'],
    contains: ['meat'],
    makesLeftovers: true,
    image: '/images/recipes/sausage-ragu.webp',
    ingredients: [
      q(i('sausages', 'protein', 'Pork sausages', 'Pork sausages'), 150, 'g'),
      q(i('fennel', 'produce', 'Fennel bulb'), 0.5, 'whole'),
      q(i('tomatoes-can', 'pantry', 'Canned crushed tomatoes', 'Tinned chopped tomatoes'), 0.5, 'cans'),
      q(onion, 0.5, 'whole'),
      q(garlic, 2, 'whole'),
      q(i('pappardelle', 'pantry', 'Pappardelle'), 90, 'g'),
      q(oliveOil, 1, 'tbsp'),
      q(i('paprika', 'pantry', 'Smoked paprika', undefined, true), 1, 'tsp'),
    ],
    steps: [
      'Squeeze the sausage meat from the skins and brown it in the olive oil, breaking it up.',
      'Add the sliced fennel, onion and garlic; soften 8 minutes.',
      'Stir in the paprika and tomatoes; simmer 15 minutes until rich.',
      'Boil the pappardelle and marry it with the ragu. Makes extra.',
    ],
  },
  {
    id: 'chicken-noodle-soup',
    name: { us: 'Chicken & ginger noodle soup' },
    time: 30,
    costPerServingUsd: 3.3,
    moods: ['cosy', 'easy'],
    contains: ['meat'],
    makesLeftovers: true,
    image: '/images/recipes/chicken-noodle-soup.webp',
    ingredients: [
      q(chicken, 120, 'g'),
      q(i('noodles', 'pantry', 'Egg noodles'), 80, 'g'),
      q(ginger, 15, 'g'),
      q(garlic, 2, 'whole'),
      q(scallions, 1, 'whole'),
      q(i('carrot', 'produce', 'Carrots'), 1, 'whole'),
      q(soy, 1, 'tbsp'),
      q(i('chicken-stock', 'pantry', 'Chicken stock'), 500, 'ml'),
    ],
    steps: [
      'Simmer the stock with the sliced ginger, garlic and carrot for 10 minutes.',
      'Add the chicken and poach gently for 12 minutes; lift out and shred.',
      'Cook the noodles in the broth, then return the chicken.',
      'Season with soy and top with scallions. Makes extra.',
    ],
  },
  {
    id: 'matar-paneer',
    name: { us: 'Matar paneer' },
    time: 30,
    costPerServingUsd: 3.6,
    moods: ['cosy'],
    contains: ['dairy'],
    makesLeftovers: false,
    image: '/images/recipes/matar-paneer.webp',
    ingredients: [
      q(i('paneer', 'dairy', 'Paneer'), 120, 'g'),
      q(i('peas', 'frozen', 'Frozen peas'), 80, 'g'),
      q(onion, 0.5, 'whole'),
      q(garlic, 2, 'whole'),
      q(ginger, 10, 'g'),
      q(i('tomatoes-can', 'pantry', 'Canned crushed tomatoes', 'Tinned chopped tomatoes'), 0.5, 'cans'),
      q(i('garam-masala', 'pantry', 'Garam masala', undefined, true), 1, 'tsp'),
      q(i('cream', 'dairy', 'Heavy cream', 'Double cream'), 50, 'ml'),
      q(rice, 90, 'g'),
    ],
    steps: [
      'Cube and pan-fry the paneer until golden; set aside.',
      'Soften the onion, garlic and ginger; add the garam masala for 30 seconds.',
      'Add the tomatoes and simmer 8 minutes; stir in the cream and peas.',
      'Return the paneer for 2 minutes and serve over rice.',
    ],
  },
  {
    id: 'chicken-caesar',
    name: { us: 'Chicken Caesar salad' },
    time: 20,
    costPerServingUsd: 4.5,
    moods: ['fresh', 'energised'],
    contains: ['meat', 'dairy'],
    makesLeftovers: false,
    image: '/images/recipes/chicken-caesar.webp',
    ingredients: [
      q(chicken, 130, 'g'),
      q(i('romaine', 'produce', 'Romaine lettuce', 'Cos lettuce'), 150, 'g'),
      q(parmesan, 20, 'g'),
      q(i('croutons', 'pantry', 'Croutons'), 30, 'g'),
      q(i('caesar-dressing', 'pantry', 'Caesar dressing'), 2, 'tbsp'),
      q(lemon, 0.25, 'whole'),
    ],
    steps: [
      'Season and pan-sear the chicken 5–6 minutes per side; rest, then slice.',
      'Chop the romaine and toss with the dressing.',
      'Top with the warm chicken, croutons and shaved parmesan.',
      'Finish with lemon zest and black pepper.',
    ],
  },
  {
    id: 'mac-cheese',
    name: { us: 'One-pan mac & cheese' },
    time: 25,
    costPerServingUsd: 2.7,
    moods: ['cosy', 'easy'],
    contains: ['dairy'],
    makesLeftovers: false,
    image: '/images/recipes/mac-cheese.webp',
    ingredients: [
      q(i('elbow-macaroni', 'pantry', 'Elbow macaroni'), 100, 'g'),
      q(i('cheddar', 'dairy', 'Cheddar'), 80, 'g'),
      q(i('milk', 'dairy', 'Whole milk'), 200, 'ml'),
      q(i('butter', 'dairy', 'Butter', undefined, true), 1, 'tbsp'),
      q(i('breadcrumbs', 'pantry', 'Breadcrumbs'), 20, 'g'),
    ],
    steps: [
      'Simmer the macaroni in the milk plus a splash of water, stirring often, until tender.',
      'Melt in the butter and most of the cheddar off the heat until glossy.',
      'Season well, scatter over the breadcrumbs and remaining cheese.',
      'Grill 3–4 minutes until the top is spotty and crisp.',
    ],
  },
  {
    id: 'chicken-traybake',
    name: { us: 'Lemon herb chicken traybake' },
    time: 40,
    costPerServingUsd: 3.7,
    moods: ['cosy'],
    contains: ['meat'],
    makesLeftovers: true,
    image: '/images/recipes/chicken-traybake.webp',
    ingredients: [
      q(chicken, 180, 'g'),
      q(i('potatoes', 'produce', 'Baby potatoes'), 250, 'g'),
      q(lemon, 1, 'whole'),
      q(garlic, 3, 'whole'),
      q(i('green-beans', 'produce', 'Green beans'), 100, 'g'),
      q(oliveOil, 1, 'tbsp'),
      q(i('oregano', 'pantry', 'Dried oregano', undefined, true), 1, 'tsp'),
    ],
    steps: [
      'Heat the oven to 220°C / 425°F. Halve the potatoes and toss with oil, oregano and halved garlic cloves.',
      'Nestle the chicken on top, season, and lay over lemon slices.',
      'Roast 25 minutes; add the green beans and roast 8 more.',
      'Rest 5 minutes, squeeze over the lemon and serve. Makes extra.',
    ],
  },
  {
    id: 'egg-ramen',
    name: { us: 'Soft egg ramen bowl' },
    time: 20,
    costPerServingUsd: 3.4,
    moods: ['cosy', 'easy'],
    contains: ['dairy'],
    makesLeftovers: false,
    image: '/images/recipes/egg-ramen.webp',
    ingredients: [
      q(i('ramen-noodles', 'pantry', 'Ramen noodles'), 100, 'g'),
      q(i('eggs', 'dairy', 'Eggs'), 2, 'whole'),
      q(scallions, 2, 'whole'),
      q(garlic, 1, 'whole'),
      q(ginger, 10, 'g'),
      q(soy, 1.5, 'tbsp'),
      q(i('sesame-oil', 'pantry', 'Toasted sesame oil', undefined, true), 1, 'tsp'),
      q(spinach, 50, 'g'),
      q(i('veg-stock', 'pantry', 'Vegetable stock'), 400, 'ml'),
    ],
    steps: [
      'Boil the eggs for 6½ minutes, then chill in cold water and peel.',
      'Simmer the stock with the ginger, garlic and soy for 5 minutes.',
      'Cook the noodles in the broth; add the spinach at the end.',
      'Divide into bowls, halve the eggs on top, finish with scallions and sesame oil.',
    ],
  },
  {
    id: 'prawn-stirfry',
    name: { us: 'Garlic prawn stir-fry', uk: 'Garlic prawn stir-fry' },
    time: 15,
    costPerServingUsd: 5.4,
    moods: ['energised', 'easy'],
    contains: ['fish'],
    makesLeftovers: false,
    image: '/images/recipes/prawn-stirfry.webp',
    ingredients: [
      q(i('prawns', 'protein', 'Prawns', 'King prawns'), 150, 'g'),
      q(garlic, 2, 'whole'),
      q(ginger, 10, 'g'),
      q(scallions, 1, 'whole'),
      q(i('broccoli', 'produce', 'Broccoli'), 100, 'g'),
      q(soy, 1.5, 'tbsp'),
      q(i('sesame-oil', 'pantry', 'Toasted sesame oil', undefined, true), 1, 'tsp'),
      q(rice, 90, 'g'),
      q(i('lime', 'produce', 'Limes'), 0.5, 'whole'),
    ],
    steps: [
      'Get the rice on. Stir-fry the broccoli in hot oil for 3 minutes.',
      'Add the garlic and ginger for 30 seconds, then the prawns.',
      'Toss until the prawns just turn pink; add the soy and sesame oil.',
      'Serve over rice with a squeeze of lime.',
    ],
  },
]

export const AISLE_LABELS: Record<Aisle, { us: string; uk: string }> = {
  produce: { us: 'Produce', uk: 'Fruit & veg' },
  protein: { us: 'Meat & seafood', uk: 'Meat & fish' },
  dairy: { us: 'Dairy & eggs', uk: 'Dairy & eggs' },
  bakery: { us: 'Bakery', uk: 'Bakery' },
  pantry: { us: 'Pantry', uk: 'Cupboard' },
  frozen: { us: 'Frozen', uk: 'Frozen' },
}

export const AISLE_ORDER: Aisle[] = ['produce', 'protein', 'dairy', 'bakery', 'pantry', 'frozen']

export function localName(value: { us: string; uk?: string }, locale: Locale) {
  return locale === 'uk' && value.uk ? value.uk : value.us
}
